### ISSUE TITLE
The "pending" status of team members cannot be altered by the those team members themselves

### ISSUE THREAD

**Issue by josephshin93** [josephshin93/codesnippets#19]
Currently, team members who have the status of pending do not have a way to alter their status. Our plan was to implement a notification system where users who are added to a team will receive a notification and have an option to accept or decline their membership to that team. Given the current development team's time constraints I propose we simply remove the pending status until we implement the notification feature in a later release.

**Comment by tibbsm** [comment]
I agree. I created a PR for removing the 'pending' role from team/member creation.

#24 Temporarily removing the pending role
