### ISSUE TITLE
Team member list should not be empty in new team form

### ISSUE THREAD

**Issue by josephshin93** [josephshin93/codesnippets#22]
There is no validation to make sure that the team member list is not empty when creating or editing a team. A more specific validation should be that the team member list should always include at least one admin. This ensures that at least one person can manage the team settings.

**Comment by tibbsm** [comment]
I think the easiest fix for this might be to automatically add the creator as an admin. I was messing around with Yup and wasn't able to find a way to require an object where role == admin.

**Comment by josephshin93** [comment]
I agree. I actually have that logic implemented in [teamRoutes.ts](https://github.com/josephshin93/codesnippets/blob/dev/routes/teamRoutes.ts) under the `/api/add_team` route, but we can move or add that logic to the team form in the frontend. Then, for the team form validation, we can use Yup to make the team members array required and have at least one element. Also, we could implement the check for the presence of at least one admin within the `onSubmit` function and use an alert to notify the user.

**Comment by josephshin93** [comment]
This issue is addressed in PR #28
