### ISSUE TITLE
Users & Teams

### ISSUE THREAD

**Issue by tibbsm** [josephshin93/codesnippets#9]
Right now when a new user signs in we create a new user without a team. To create a snippet you need now need a team in order to complete the form. 

1) When you go to the snippet form without any teams on your user profile, the page won't load due to an error. This can be solved easily by checking to see if a user has any teams. (NewSnippet.tsx : Line 18)

2) Even when the page loads, a user without any teams won't be able to complete the form as they can't select anything for the team field, which is a required field. 

Off the top of my head, I think we can potentially initialize every user with a 'Personal' team, so that they can post snippets that apply only to themselves or we can make the team field an optional field to fill in.

**Comment by wanahmaw** [comment]
I forgot about New Users having no team upon creation.

For now the form's select dropdown option will default to Personal if user has no teams. Potential plan to use Google Cloud Functions to initialize every new user with a 'Personal' team.

Forms now load with our without teams field

**Comment by tibbsm** [comment]
Perfect. This should work for now. Another issue this might create is that if each user has a 'personal' team we would have a bunch duplicate personal team entities in our db.

**Comment by wanahmaw** [comment]
Good call. What are your thoughts on how we should structure snippets without a team?

In terms of a Snippet document, I felt fine to have many teams field as 'personal'. It would be easy to find someone's personal snippets with a query like 'Get snippets where owner is John and team is Personal'.

In terms of a Teams collection, there should not be any Team documents with ID of 'Personal'. So in essence, we're using the Snippet's team field of 'Personal' as a keyword that it strictly belongs to the owner.

Perhaps the User document should not have a teams array with 'Personal' after all?

Let me know where you're coming from though, maybe I'm thinking about this the wrong way

**Comment by tibbsm** [comment]
Sounds good! Didn't think of just using the personal team as a tag. This way we don't have to mess with how we're initializing new users or worry about the duplicate personal teams in the teams collection.
